export default {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Munchkin White Hot Safety Bath Ducky',
      category: 'Rubber',
      image: '/images/product-1.jpg',
      price: 6.99,
      brand: 'Munchkin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2222222222',
      name: 'Vermont Teddy Bear Cuddly Toy',
      category: 'Plush',
      image: '/images/product-2.jpg',
      price: 14.99,
      brand: 'Vermont Teddy Bear',
      rating: 5,
      numReviews: 51,
      countInStock: 8,
    },
    {
      _id: '33333333',
      name: 'Aurora - Cuddly Friends',
      category: 'Plush',
      image: '/images/product-3.jpg',
      price: 12.99,
      brand: 'Aurora',
      rating: 4,
      numReviews: 45,
      countInStock: 3,
    },
    {
      _id: '44444444',
      name: 'Batman Rubber Bath Duck',
      category: 'Rubber',
      image: '/images/product-4.jpg',
      price: 10.99,
      brand: 'Paladone Products Ltd',
      rating: 2.5,
      numReviews: 198,
      countInStock: 4,
    },
    {
      _id: '55555555',
      name: 'Ensky My Neighbor Totoro Totoro',
      category: 'Rubber',
      image: '/images/product-5.jpg',
      price: 19.99,
      brand: '	Ensky',
      rating: 3.5,
      numReviews: 89,
      countInStock: 2,
    },
    {
      _id: '66666666',
      name: 'Kaiyodo Revoltech Danboard Mini Yotsuba',
      category: 'Figure',
      image: '/images/product-6.jpg',
      price: 150,
      brand: 'Kaiyodo',
      rating: 4.5,
      numReviews: 45,
      countInStock: 1,
    },
  ],
};
